from typing import Literal, List, overload
import naoqi

# mypy stub file for the qi API.
# Lets the mypy type checker reason about interactions with NAO.
# Add methods here as we need them.
# Note: Always import as `qi`. Some of the classes below don't technically exist.

# More about mypy stubs:
# https://mypy.readthedocs.io/en/stable/stubs.html

class QIFuture:
    def cancel(self) -> None: ...
    def wait(self) -> None: ...
    def isRunning(self) -> bool: ...

class Application:
    session: Session
    def __init__(self, args: List[str]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class Session:
    @overload
    def service(self, name: Literal["ALAudioDevice"]) -> naoqi.ALAudioDevice: ...
    @overload
    def service(
        self, name: Literal["ALBehaviorManager"]
    ) -> naoqi.ALBehaviorManager: ...
    @overload
    def service(self, name: Literal["ALAudioPlayer"]) -> naoqi.ALAudioPlayer: ...
    @overload
    def service(self, name: Literal["ALRobotPosture"]) -> naoqi.ALRobotPosture: ...
    @overload
    def service(self, name: Literal["ALLeds"]) -> naoqi.ALLeds: ...
    @overload
    def service(self, name: Literal["ALMemory"]) -> naoqi.ALMemory: ...
    @overload
    def service(self, name: Literal["ALSoundDetection"]) -> naoqi.ALSoundDetection: ...
    @overload
    def service(self, name: Literal["ALAudioRecorder"]) -> naoqi.ALAudioRecorder: ...
    @overload
    def service(self, name: Literal["ALTextToSpeech"]) -> naoqi.ALTextToSpeech: ...
